# Generated by Django 5.2.1 on 2025-05-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_rename_product_name_products_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='category_reference',
        ),
    ]
